### ISSUE TITLE
MacOS - login broken

### ISSUE THREAD

**Issue by kbaegis** [Igor-Kotv/VlcPlugin#4]
Can't login. LUA interface on some random http port redirects to `/?`

**Comment by kbaegis** [comment]
Prefer to set this manually in the config files.

VLC RC file: `~/Library/Preferences/org.videolan.vlc/vlcrc`
....
```
[lua]
http-password=<some value>

[core]
extraintf=http
```
Now it's just in an endless auth loop:
http://localhost:3100/ -> http://localhost:3100/?

Where is _your_ config file stored?

**Comment by kbaegis** [comment]
Found some files at `~/.local/share/Loupedeck/PluginSettings`, but wasn't able to figure out the encoding.

**Comment by kbaegis** [comment]
Figured out what you were doing. Just navigated manually to loupedeck:plugin/Vlc/callback/setPassword?<password-plaintext>

**Comment by Igor-Kotv** [comment]
> Can't login. LUA interface on some random http port redirects to `/?`

I am able to login. Please follow the instruction in the README file of this repository. Please make sure that all software is updated (Loupedeck configuration, VLC media player and VLC plugin - installed from Loupedeck Markerplace)
