### ISSUE TITLE
Jog defect

### ISSUE THREAD

**Issue by kbaegis** [Igor-Kotv/VlcPlugin#5]
The jog feature does not pull current time data from the VLC playing track prior to starting jog/seek commands. As such, if the previous track was at 5:00 minutes, as an example, and you jog- it won't detect the change in the time and will skip either to 5:00 minutes on the next track or to the very end.

**Comment by Igor-Kotv** [comment]
> The jog feature does not pull current time data from the VLC playing track prior to starting jog/seek commands. As such, if the previous track was at 5:00 minutes, as an example, and you jog- it won't detect the change in the time and will skip either to 5:00 minutes on the next track or to the very end.

thanks for sharing, I will check this

**Comment by Igor-Kotv** [comment]
fixed in v1.2.0
